#!/usr/bin/env bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy initial conditions
cp -rf 0.org 0

runApplication blockMesh

if [ "$1" = "-parallel" ]
    runApplication decomposePar
    runParallel snappyHexMesh -overwrite
    runParallel topoSet
    then
    if [[ $WM_PROJECT_VERSION == "3."* ]]
        then
        nProc=$(getNumberOfProcessors)
    else
        nProc=""
    fi
    ls -d processor* | xargs -I {} rm -rf ./{}/0
    ls -d processor* | xargs -I {} cp -r 0.org ./{}/0
    runParallel pimpleFoam  $nProc
else
    runApplication snappyHexMesh -overwrite
    runApplication topoSet
    runApplication pimpleFoam
fi
